# Generated by Django 3.0.6 on 2020-07-17 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('preco', models.CharField(max_length=6)),
                ('cadastrado', models.DateTimeField(default=django.utils.timezone.now)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('disponível', 'Disponível'), ('indisponível', 'Indisponível')], default='indisponível', max_length=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
