# Generated by Django 3.0.6 on 2020-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(max_length=10),
        ),
    ]
